### ISSUE TITLE
License File Needed

### ISSUE THREAD

**Issue by mcvangelder** [mmajcica/ExpectedAggregateExceptionAttribute#1]
I came across your blog the other day when trying to search for an attribute to check inner exceptions for AggregatedExceptions thrown in unit tests.

I would love to be able to use this attribute, however, my company requires explicit permission or a license file to be able to use the opensource code in our product.

Thanks.

**Comment by mmajcica** [comment]
Sure, no problem. I'll set the most permissive licence tomorrow morning.

**Comment by mcvangelder** [comment]
Thank you, that is appreciated!

**Comment by mmajcica** [comment]
Done. Check if MIT is good enough.

**Comment by mcvangelder** [comment]
Yes, MIT should be good enough. Thanks!
